name: Run WhatsApp Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */5 * * *" # every 5 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Clone Private Repo
        run: |
          git clone https://${{ secrets.TOKEN }}@github.com/nbbb15092/Bb.git bot

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd bot
          npm install

      - name: Start Bot
        run: |
          cd bot
          node index.js
        env:
          COLLECTION_NAME: sfolder2_sessions
